/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int DEF_TOKEN = 2;
  /** RegularExpression Id. */
  int SPACE = 3;
  /** RegularExpression Id. */
  int MAIN_TOKEN = 4;
  /** RegularExpression Id. */
  int PARAM_NAME = 5;
  /** RegularExpression Id. */
  int FUNC_NAME = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int ARG_NAME = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "\"DEF\"",
    "\" \"",
    "\"MAIN\"",
    "<PARAM_NAME>",
    "<FUNC_NAME>",
    "<NUM>",
    "<ARG_NAME>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"(\"",
    "\"+\"",
    "\"*\"",
    "\")\"",
  };

}
